#! /bin/bash

sxhkd &
picom &
polybar main &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
#xwinwrap -fs -fdt -ni -b -nf -un -ov -o 1.0 -debug -- mpv -wid WID --loop --no-audio /home/tihon/Загрузки/stockvideo_05469.mov &

bspc monitor -d 1 2 3 4 5

bspc config border_width                  2
bspc config window_gap                    10

bspc config normal_border_color           "#171518"
bspc config active_border_color           "#171518"
bspc config focused_border_color          "#171518"

bspc config single_monocle                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       16