#! /bin/sh

uptime="`uptime -p | sed -e 's/up //g'`"

rofi_cmd() {
	rofi -dmenu \
		-p "Uptime: $uptime" \
		-mesg "Uptime: $uptime" \
		-theme ~/.config/rofi/power.rasi
}

chosen=$(printf "\n\n" | rofi_cmd)

#chosen=$(printf "\n\n" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"") poweroff ;;
	"") reboot ;;
	"") loginctl terminate-session 1 ;;
	*) exit 1 ;;
esac