#! /bin/bash

#АВТОСТАРТ
sxhkd &
numlockx &
nitrogen --restore &
polybar power &
polybar main &
picom &
xsetroot -cursor_name left_ptr &

#ВОРКСПЕЙСЫ
bspc monitor -d   ⚫️ ⚫️ ⚫️ ⚫️ ⚫️ 


#РАМКИ И ГАПСЫ
bspc config border_width         0
bspc config window_gap          9

bspc config normal_border_color "#373737"
bspc config active_border_color "#373737"
bspc config focused_border_color "#373737"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНА
bspc config presel_feedback_color "fd2e59"

#ОТСТУПЫ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+9))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+2))
#bspc config bottom_padding -$(($gap-9)



#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5
#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true


#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral


#ПРАВИЛА ОКОН
bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
bspc rule -a Steam state=floating follow=off rectangle=1350x900+285+90 desktop='^6'
bspc rule -a Discord state=floating follow=off rectangle=1350x900+285+90 desktop='^6' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
bspc rule -a Blender desktop='^2'
